### ISSUE TITLE
After i downloaded the apk and try to install it it says "app not installed" with no other info as to why.

### ISSUE THREAD

**Issue by ItsAndroids** [2394425147/maipaddx#43]
**Describe the bug**

**To Reproduce**
1.

**Expected behavior**

**Screenshots**

**Device specs**

**Additional context**

**Comment by Soneoylys** [comment]
Please provide more detail.
Sounds like your device not meet minimum requirement, either due to system version or hardware spec.

**Comment by 2394425147** [comment]
Hello, if you're updating AstroDX from an older version (2.0.0.dev, or 1.0), you'll need to uninstall the old application and install the new one, due to signature conflicts.

If you want to preserve your game data (scores, etc.), check out this guide:
[1.x/2.0.0.dev to 2.0.0.pre.beta migration guide](https://github.com/2394425147/maipaddx/wiki/Importing-levels#1x200dev-to-200prebeta-migration-guide)

Hope this solves your issue!

**Comment by Soneoylys** [comment]
Close this issue due to no further reply,
You can reopen by reply to this issue anytime again.
Thanks for reporting!
