### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by sorae42** [2394425147/maipaddx#5]
Will there be an ipa file so we don't have to wait for the TestFlight slot?

**Comment by huajip** [comment]
Since someone has a history of trying to publicly decrypt and release ipa, and the developer responsible for releasing testflight once refused to provide an ipa to a player with bad behavior, the developer was directly searched by human flesh, so we do not consider releasing ipa Please wait  The main developer is over 18 years old, and we do not advocate the behavior of decrypting the public release of the ipa. If someone does this, the testflight qualification will be revoked, please keep a low profile, we do not want the game to be publicized in large quantities
