### ISSUE TITLE
Add a new functionality that users can make their own fumen on mobile devices similar to majdata.

### ISSUE THREAD

**Issue by FYNIXqwq** [2394425147/maipaddx#68]
I really wonder how convenient for a note designer to make fumen on a tablet such as iPad. Therefore I suggest AstroDX develop a new functionality that users can make their own fumen with a mobile-optimised interface.

The rough picture of the interface is below.

![IMG_2914](https://github.com/2394425147/maipaddx/assets/51454565/dbd00ecf-53d5-4363-b377-a7e2fa979d8a)

The display is divided into simai note editor and a fumen viewer. 
Users can edit the fumen by simai format with the keyboard designed for its syntax, similar to majdata. The viewer plays the fumen in the editor, and a time axis showing the note distribution is below the viewer where users can drag it, or zoom in/out by 2 fingers. The play/pause button and the stop button is at the corner. 
The Auto Play / Player Test switch can change the preview mode. The former is to play the fumen automatically and the latter is to play by designers themselves. When it's switched to Player Test mode, the pause and the stop button should be triggered when pressed 3 seconds or longer continuously to avoid mistakes, and the other parts of the preview area and the whole editor is disabled under Player Test mode.

I've used majdata to make fumen for 2 years, and many inconvenience are found (indeed majdata is powerful and more professional, which is without doubt). For instance, PC are usually heavier than mobile devices and requires more time to start working. The editor mode of AstroDX can be designed as a convenient version of majdata.

**Comment by DavidScann** [comment]
We've actually thought about implementing editor mode, (it's actually on #roadmap in the AstroDX Discord server, under the No ETA section) but it's a low priority task for now, hence the no ETA.
Thank you for the layout idea, though! We'll take this into consideration.

A separate charting program development has been started with [AstroCreate.](https://github.com/xhayper/AstroCreate/) (of no official affiliation with us) (development has also been paused for a while because the developer is now working on AstroDX with us), so if you know how to develop programs, you can contribute to that repo too. I'm sure he'll appreciate it.

If this answer is satisfactory, please close the issue 🙏 Thank you!
